[package]
name = "termformat"
version = "0.0.1"
authors = ["Andrew Hobden <andrew@hoverbear.org>"]
description = "A simple command line terminal text formatter."

[dependencies]
clap = "*"
term = "*"
error-chain = "*"
